/* Automatically generated by configure - do not modify */
#include "config-host.h"

#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-i386"
#define TARGET_ARCH "i386"
#define TARGET_I386 1
#define CONFIG_SOFTMMU 1
#define CONFIG_SDL 1

//#define HAS_AUDIO
//#define HAS_AUDIO_CHOICE
//#define CONFIG_SB16
//#define CONFIG_AC97
//#define CONFIG_ES1370

//#define FLOATX80

#ifdef _MSC_VER
#define asm(X)

#define private __private
#define snprintf _snprintf
#endif